#!/bin/bash
process() {
	tr -d ' \n' | sed 's/\(.\)/\1\n/g'
}

diff --minimal -u1000000 <(ao abcRaw $1 | process) <(ao abc $1 | process) | tail -n+4 | sed 's/-\(.\)/[31m\1[0m/' | sed 's/+\(.\)/[32m\1[0m/' | tr -d ' \n'
echo
