#!/bin/bash
process() {
	tr -d ' \n' | sed 's/\(.\)/\1\n/g'
}

GREEN="[32m"
RED="[31m"
NORMAL="[0m"

diff --minimal -u1000000 <(ao abc.raw "$@" | process) <(ao abc "$@" | process) | tail -n+4 | sed "s/-\(.\)/${RED}\1${NORMAL}/" | sed "s/+\(.\)/${GREEN}\1${NORMAL}/" | tr -d ' \n'
echo
