#!/bin/bash
# Create a C source file that contains a string constant whose contents is that
# of the file given by the first argument.

if [[ $# != 1 ]]; then
	echo "No arguments passed to $0"
	exit 1
fi

filename="$1"
output="${filename%.*}.gen.c"
variable="$(echo -n "${filename##*/}" | tr '.-' '_')"


read -r -d '' script <<'EOF' || true
s/\\/\\\\/g;
s/"/\\"/g;
s/^.*$/"&\\n"/;
EOF
sed -e "$script" < "$filename" | cat <(echo "extern char *$variable; char *$variable = ") - <(echo ";") > "$output"
