#!/bin/bash
set -e
mkdir -p words
rm -f words/*
time ao list '*' | while read -r w
do
	if grep -F -x -q -- "$w" word-blacklist; then
		#skip
		echo "$w -- BLACKLISTED"
	else
		echo "$w"
		ao abc.ann "$w" > words/w-"$(echo "$w" | tr '/' '@')"
	fi
done
