#!/bin/bash
set -e -o pipefail

TMPSRC=$(mktemp --suffix=.c)
RTSFILES="
	rts/rt0.s
	rts/syscall.s
	rts/syscalls.c
	rts/rts.c
"

cabal build
AO_DICT=abcc AO_PATH="./ao:$AO_PATH" ao abc "$@" | ./dist/build/abcc/abcc > $TMPSRC
# With gcc, pass -falign-functions=4 so that we have free bits in the function pointers.
clang -std=c99 -march=native -msse4.1 -ffreestanding -nostdlib -O3 -static -Wall -Wextra -g -o abc.out -Irts $RTSFILES $TMPSRC
echo Running
gdb -batch -x /dev/stdin ./abc.out 1>&2 <<"SCRIPT"
set confirm off
source gdb.py
run
if $_isvoid($_exitcode)
    print-abc-value v
    quit 1
end
SCRIPT
echo Done
rm $TMPSRC
rm abc.out
